name: Deploy HomeServices Fullstack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "=== Deploying HomeServices App ==="
            sudo apt-get update -y

            # Install Docker if missing
            if ! command -v docker &> /dev/null; then
              sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ubuntu
            fi

            # Install Docker Compose if missing
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Project directory
            mkdir -p ~/home_services_app
            cd ~/home_services_app

            # Copy updated files
            rsync -avz --delete $GITHUB_WORKSPACE/ .

            # Stop existing containers
            sudo docker-compose down || true

            # Remove unused containers/networks
            sudo docker system prune -f || true

            # Build & start containers
            sudo docker-compose up -d --build

            # Show status & logs
            sleep 30
            sudo docker-compose ps
            sudo docker-compose logs backend --tail=20
            sudo docker-compose logs frontend --tail=20